FROM gradle:8.12-jdk21

# Install required tools
RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /build

# Default command
CMD ["gradle", "clean", "build"]