services:
  paper:
    image: itzg/minecraft-server
    container_name: minecraft-paper
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: "1.21.1"
      MEMORY: 2G
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD:-takaro123}"
      RCON_PORT: 25575
      ONLINE_MODE: "false"
      TAKARO_WS_URL: "${TAKARO_WS_URL}"
      TAKARO_REGISTRATION_TOKEN: "${TAKARO_REGISTRATION_TOKEN}"
      TAKARO_IDENTITY_TOKEN: "takaro-paper-dev"
    volumes:
      - ./_data/paper:/data
    restart: unless-stopped
    tty: true
    stdin_open: true

  neoforge:
    image: itzg/minecraft-server
    container_name: minecraft-neoforge
    ports:
      - "25566:25565"
      - "25576:25575"
    environment:
      EULA: "TRUE"
      TYPE: NEOFORGE
      VERSION: "1.21.1"
      MEMORY: 2G
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD:-takaro123}"
      RCON_PORT: 25575
      ONLINE_MODE: "false"
      TAKARO_WS_URL: "${TAKARO_WS_URL}"
      TAKARO_REGISTRATION_TOKEN: "${TAKARO_REGISTRATION_TOKEN}"
      TAKARO_IDENTITY_TOKEN: "takaro-neoforge-dev"
    volumes:
      - ./_data/neoforge:/data
    restart: unless-stopped
    tty: true
    stdin_open: true

  fabric:
    image: itzg/minecraft-server
    container_name: minecraft-fabric
    ports:
      - "25567:25565"
      - "25577:25575"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: "1.21.1"
      MODRINTH_PROJECTS: "fabric-api"
      MEMORY: 2G
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD:-takaro123}"
      RCON_PORT: 25575
      ONLINE_MODE: "false"
      TAKARO_WS_URL: "${TAKARO_WS_URL}"
      TAKARO_REGISTRATION_TOKEN: "${TAKARO_REGISTRATION_TOKEN}"
      TAKARO_IDENTITY_TOKEN: "takaro-fabric-dev"
    volumes:
      - ./_data/fabric:/data
    restart: unless-stopped
    tty: true
    stdin_open: true
