modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "takaro"
version = "${version}"
displayName = "Takaro Minecraft Connector"
description = "Takaro game server connector for NeoForge"

[[dependencies.takaro]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.takaro]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "SERVER"
